name: "Simple Shell Syntax Check"
author: "Søren Klintrup <soren@klintrup.dk>"
description: "Uses shell '-n' to syntax check shellscripts"
branding:
  icon: "terminal"
  color: "gray-dark"
inputs:
  files:
    description: "Files to check"
    required: false
    default: ""
  install_missing_shell:
    description: "identify shell and install if missing"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name:  install missing shell
      shell: bash
      # only run if install_missing_shell is true and if os is ubuntu
      if:    ${{ (inputs.install_missing_shell == 'true') && (runner.os == 'Linux') }} 
      run:   ${{ github.action_path }}/install-shell-from-shebang.sh ${{ inputs.files }}
    - name:  run simple-shell-syntax-check.sh
      shell: bash
      run:   ${{ github.action_path }}/simple-shell-syntax-check.sh ${{ inputs.files }}
