
name: "Simple Shell Syntax Check"
author: "Søren Klintrup <soren@klintrup.dk>"
description: "Uses shell '-n' to syntax check shellscripts"
branding:
  icon: "terminal"
  color: "gray-dark"

inputs:
  files:
    description: "Files to check"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name:  run simple-shell-syntax-check.sh
      shell: bash
      run:  |
       for file in ${{ inputs.files }}; do
          echo ${file}
       done | xargs -n100 -P1 .github/scripts/simple-shell-syntax-check.sh
