
name: "simple-shell-syntax-check"
author: "Søren Klintrup <soren@klintrup.dk>"
description: "Uses shell '-n' to syntax check shellscripts"

inputs:
  files:
    description: "Files to check"
    required: false
    default: ""

runs:
  # using: "composite"
  # steps:
    # - name:  make script executable
    #   shell: bash
    #   run:   chmod +x .github/scripts/simple-shell-syntax-check.sh
    # - name:  run simple-shell-syntax-check.sh
    #   shell: bash
    #   run:   .github/scripts/simple-shell-syntax-check.sh ${{ inputs.files }}
  using: 'docker'
  image: ghcr.io/klintrup/simple-shell-syntax-check:pr-1
  args:
    - ${{ inputs.files }}
