
name: "simple-shell-syntax-check"
author: "Søren Klintrup <soren@klintrup.dk>"
description: "Uses shell '-n' to syntax check shellscripts"

runs:
  using: "composite"
  steps:
    - name: Verify script syntax
      shell: bash
      run: .github/scripts/simple-shell-syntax-check.sh
