on:
  pull_request:
  push:
    branches: [ main ]

name: lint-shell

permissions:
  contents: read

jobs:
  list-files:
    name: list-files
    runs-on: ubuntu-latest
    outputs:
      sh-changed-files:  ${{ steps.changed-files-sh.outputs.all_changed_files }}
      sh-any-changed:    ${{ steps.changed-files-sh.outputs.any_changed }}
      md-changed-files:  ${{ steps.changed-files-md.outputs.all_changed_files }}
      md-any-changed:    ${{ steps.changed-files-md.outputs.any_changed }}
      sh-examples:       ${{ steps.find-examples-sh.outputs.sh-examples }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files-sh
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.sh
      - name: matrix-changed-sh
        id:   matrix-changed-sh
        run:  |
                (
                  echo -n "files={\"include\":["
                  for filename in ${{ steps.changed-files-sh.outputs.all_changed_files }}
                  do
                    echo -n "{ \"filename\": \"${filename}\" }, "
                  done
                  echo -n "]}" 
                ) | tee -a ${GITHUB_OUTPUT}
      - name: Get changed files
        id: changed-files-md
        uses: tj-actions/changed-files@v40
        with:
          files: |
             **.md
      - name: find examples
        id:   find-examples-sh
        run:  |
                echo "sh-examples<<EOF"     >> ${GITHUB_OUTPUT}
                find examples/ -name '*.sh' -type f >> ${GITHUB_OUTPUT}
                echo "EOF"                  >> ${GITHUB_OUTPUT}
  sh-verify-examples:
    name: sh-verify-examples
    runs-on: ubuntu-latest
    needs: list-files
    steps:
      - uses: actions/checkout@v4
      - name: Install fish ksh zsh
        run: sudo apt-get install -y fish ksh zsh
      - name: syntax
        id:   syntax
        uses: ./
        with:
          files: "${{ needs.list-files.outputs.sh-examples }}"
  sh-check-changed:
    name: Check changed files
    needs: [ list-files ]
    if:    needs.list-files.outputs.sh-any-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install fish ksh zsh
        run:  sudo apt-get install -y fish ksh zsh
      - name: Check syntax
        uses: ./
        with:
          files: ${{ needs.list-files.outputs.sh-changed-files }}
  prettier:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if:   needs.list-files.outputs.md-any-changed == 'true'
    needs: list-files
    steps:
      - uses: actions/checkout@v4
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ${{ needs.list-files.outputs.md-changed-files }}
