on:
  pull_request:

name: lint-markdown
permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
             '**.md'
      - name: Prettify code
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ${{ steps.changed-files.outputs.all_changed_files }}
