on:
  pull_request:

name: lint-shell
permissions:
  contents: write

jobs:
  sh:
    name: simple-shell-syntax-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.sh
      - name: Install fish
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt-get -y install fish
      - name: Install ksh
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt-get -y install ksh
      - name: Install zsh
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt-get -y install zsh
      - uses: Klintrup/simple-shell-syntax-check@move-payload-to-script
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          
          
