on:
  pull_request:
  push:
    branches: [ main ]

name: lint-shell

permissions:
  contents: read

jobs:
  list-files:
    name: list-files
    runs-on: ubuntu-latest
    outputs:
      sh-changed-files: ${{ steps.changed-files-sh.outputs.all_changed_files }}
      sh-any-changed:   ${{ steps.changed-files-sh.outputs.any_changed }}
      md-changed-files: ${{ steps.changed-files-md.outputs.all_changed_files }}
      md-any-changed:   ${{ steps.changed-files-md.outputs.any_changed }}
      sh-examples:      ${{ steps.matrix-examples-sh.outputs.files }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files-sh
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.sh
      - name: Get changed files
        id: changed-files-md
        uses: tj-actions/changed-files@v40
        with:
          files: |
             **.md
      - name: find examples
        id:   matrix-examples-sh
        run:  |
                (
                  echo -n "files={\"include\":[{"
                  for filename in $(find examples/ -name '*.sh')
                  do
                    echo -n "\"filename\": \"${filename}\", "
                  done|sed s/,$//
                  echo -n "}]}" 
                ) | tee -a ${GITHUB_OUTPUT}
  sh-verify-examples:
    name: sh-verify-examples
    runs-on: ubuntu-latest
    needs: list-files
    strategy:
      matrix: "${{fromJson(needs.list-files.outputs.sh-examples)}}"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/find-shell-from-shebang/
        id: find-shell
        with:
          files: "${{ matrix.filename }}"
      - name: Install fish
        if:   startsWith("${{ steps.find-shell.outputs.shell }}", "fish") == "true"
        run: sudo apt-get install -y fish
      - name: Install ksh
        if:   startsWith("${{ steps.find-shell.outputs.shell }}", "ksh") == "true"
        run: sudo apt-get install -y ksh
      - name: Install zsh
        if:   startsWith("${{ steps.find-shell.outputs.shell }}", "zsh") == "true"
        run: sudo apt-get install -y zsh
      - name: syntax-${{ matrix.filename }}
        id:   matrix-syntax
        uses: ./
        with:
          files: ${{ matrix.filename }}
  sh-check-changed:
    name: Check changed files
    needs: [ list-files, sh-verify-examples ]
    if:    needs.list-files.outputs.sh-any-changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: ${{ needs.list-files.outputs.sh-changed-files }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/find-shell-from-shebang/
        id: find-shell
        with:
          file: ${{ matrix.filename }}
      - name: Install fish
        if:   startsWith(${{ steps.find-shell.outputs.shell }}, fish) == true
        run: sudo apt-get install -y fish
      - name: Install ksh
        if:   startsWith(${{ steps.find-shell.outputs.shell }}, ksh) == true
        run: sudo apt-get install -y ksh
      - name: Install zsh
        if:   startsWith(${{ steps.find-shell.outputs.shell }}, zsh) == true
        run: sudo apt-get install -y zsh
      - name: Check syntax
        uses: ./
        if:   needs.list-files.outputs.sh-any-changed == 'true'
        with:
          files: ${{ matrix.filename }}
  prettier:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: list-files
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prettify code
        if:   needs.list-files.outputs.md-any-changed == 'true'
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ${{ needs.list-files.outputs.md-changed-files }}
